---
title: "Homework_7"
author: "Gavin Briske"
date: "3/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2) 
library(MASS) 

```


```{r}

z<-iris

p1 <- ggplot(data=z, aes(x=Sepal.Length, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) 
print(p1)

p1 <-  p1 +  geom_density(linetype="dotted",size=0.75)
print(p1)


normPars <- fitdistr(z$Sepal.Length,"normal")
print(normPars)
str(normPars)
normPars$estimate["mean"] # note structure of getting a named attribute


meanML <- normPars$estimate["mean"]
sdML <- normPars$estimate["sd"]

xval <- seq(0,max(z$Sepal.Length),len=length(z$Sepal.Length))

 stat <- stat_function(aes(x = xval, y = ..y..), fun = dnorm, colour="red", n = length(z$Sepal.Length), args = list(mean = meanML, sd = sdML))
 p1 + stat
 
 
 
 expoPars <- fitdistr(z$Sepal.Length,"exponential")
rateML <- expoPars$estimate["rate"]

stat2 <- stat_function(aes(x = xval, y = ..y..), fun = dexp, colour="blue", n = length(z$Sepal.Length), args = list(rate=rateML))
 p1 + stat + stat2
 
 
 stat3 <- stat_function(aes(x = xval, y = ..y..), fun = dunif, colour="darkgreen", n = length(z$Sepal.Length), args = list(min=min(z$Sepal.Length), max=max(z$Sepal.Length)))
 p1 + stat + stat2 + stat3

 
 gammaPars <- fitdistr(z$Sepal.Length,"gamma")
shapeML <- gammaPars$estimate["shape"]
rateML <- gammaPars$estimate["rate"]

stat4 <- stat_function(aes(x = xval, y = ..y..), fun = dgamma, colour="brown", n = length(z$Sepal.Length), args = list(shape=shapeML, rate=rateML))
 p1 + stat + stat2 + stat3 + stat4
 
 
pSpecial <- ggplot(data=z, aes(x=Sepal.Length/(max(Sepal.Length + 0.1)), y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) + 
  xlim(c(0,1)) +
  geom_density(size=0.75,linetype="dotted")

betaPars <- fitdistr(x=z$Sepal.Length/max(z$Sepal.Length + 0.1),start=list(shape1=1,shape2=2),"beta")
shape1ML <- betaPars$estimate["shape1"]
shape2ML <- betaPars$estimate["shape2"]

statSpecial <- stat_function(aes(x = xval, y = ..y..), fun = dbeta, colour="orchid", n = length(z$Sepal.Length), args = list(shape1=shape1ML,shape2=shape2ML))
pSpecial + statSpecial


```

